name: CI/CD Calidad SoftWare

on:
  push:
    branches: ["master" ]
  pull_request:
    branches: ["master" ]

jobs:
  quality-check:
    name: Validaci贸n de Calidad
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del c贸digo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Validar formato con Checkstyle
      run: mvn checkstyle:check
      continue-on-error: false
    
    - name: Compilar el proyecto
      run: mvn compile
      continue-on-error: false
    
    - name: Ejecutar pruebas unitarias
      run: mvn test -B
      continue-on-error: false
    
    - name: Generar informe de cobertura
      run: mvn jacoco:report
      continue-on-error: false
    
    - name: Verificar cobertura de c贸digo
      run: mvn jacoco:check
      continue-on-error: false
    
    - name: Empaquetar la aplicaci贸n
      run: mvn package -DskipTests
      continue-on-error: false
    
    - name: Subir informe de cobertura
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: target/site/jacoco/
        retention-days: 7
    
    - name: Subir informe de Checkstyle
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-report
        path: target/checkstyle-result.xml
        if-no-files-found: warn
        retention-days: 7
